"""init schema

Revision ID: 7c7327e5805f
Revises: 
Create Date: 2026-07-13 11:26:02.963938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7c7327e5805f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('address_input', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('consented_to_contact', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_logs_email'), 'diagnosis_logs', ['email'], unique=False)
    op.create_table('medical_institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prefecture', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_institutions_department'), 'medical_institutions', ['department'], unique=False)
    op.create_index(op.f('ix_medical_institutions_prefecture'), 'medical_institutions', ['prefecture'], unique=False)
    op.create_table('population_mesh',
    sa.Column('mesh_code', sa.String(), nullable=False),
    sa.Column('prefecture', sa.String(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mesh_code')
    )
    op.create_index(op.f('ix_population_mesh_prefecture'), 'population_mesh', ['prefecture'], unique=False)
    op.create_table('population_mesh_age',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesh_code', sa.String(), nullable=False),
    sa.Column('age_bracket', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mesh_code'], ['population_mesh.mesh_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_population_mesh_age_mesh_code'), 'population_mesh_age', ['mesh_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_population_mesh_age_mesh_code'), table_name='population_mesh_age')
    op.drop_table('population_mesh_age')
    op.drop_index(op.f('ix_population_mesh_prefecture'), table_name='population_mesh')
    op.drop_table('population_mesh')
    op.drop_index(op.f('ix_medical_institutions_prefecture'), table_name='medical_institutions')
    op.drop_index(op.f('ix_medical_institutions_department'), table_name='medical_institutions')
    op.drop_table('medical_institutions')
    op.drop_index(op.f('ix_diagnosis_logs_email'), table_name='diagnosis_logs')
    op.drop_table('diagnosis_logs')
    # ### end Alembic commands ###
